# Generated by Django 5.2.17 on 2026-09-14 07:36

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Anomaly",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "parameter",
                    models.CharField(
                        choices=[
                            ("TEMPERATURE", "Temperature Sensor"),
                            ("HUMIDITY", "Humidity Sensor"),
                            ("PRESSURE", "Pressure Sensor"),
                            ("MULTIVARIATE", "Multivariate Thermodynamic Consistency"),
                            ("SPATIAL", "Spatial Consensus Divergence"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "classification",
                    models.CharField(
                        choices=[
                            ("NORMAL", "Normal Weather Pattern"),
                            ("GENUINE_WEATHER_EVENT", "Genuine Extreme Weather Event"),
                            ("SENSOR_FAULT", "Sensor Hardware / Calibration Fault"),
                            ("DATA_ISSUE", "Data Transmission / Corrupted Packet"),
                        ],
                        default="NORMAL",
                        max_length=30,
                    ),
                ),
                (
                    "fault_type",
                    models.CharField(
                        choices=[
                            ("NONE", "None / Normal"),
                            ("SPIKE", "Spike / Sudden Jump"),
                            ("DROP", "Drop / Sudden Dip"),
                            ("FROZEN", "Frozen / Flatline Sensor"),
                            ("DRIFT", "Sensor Drift / Monotonic Bias"),
                            ("MISSING_DATA", "Missing Data / Null Gap"),
                            ("COMMUNICATION_FAILURE", "Communication Failure"),
                            ("CORRUPTED_DATA", "Corrupted Data Packet"),
                            ("CALIBRATION_ISSUE", "Out of Calibration Range"),
                        ],
                        default="NONE",
                        max_length=30,
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("LOW", "Low Severity"),
                            ("MEDIUM", "Medium Severity"),
                            ("HIGH", "High Severity"),
                            ("CRITICAL", "Critical Severity"),
                        ],
                        default="LOW",
                        max_length=15,
                    ),
                ),
                (
                    "anomaly_score",
                    models.FloatField(
                        default=0.0, help_text="Normalized anomaly score (0.0 to 1.0)"
                    ),
                ),
                (
                    "confidence",
                    models.FloatField(
                        default=0.0,
                        help_text="Confidence of decision engine (0.0 to 1.0)",
                    ),
                ),
                (
                    "explanation",
                    models.TextField(
                        help_text="Human-readable explainable AI diagnostic explanation"
                    ),
                ),
                (
                    "recommended_action",
                    models.TextField(
                        blank=True,
                        help_text="Actionable maintenance/operational advice",
                    ),
                ),
                (
                    "detected_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Anomalies",
                "ordering": ["-detected_at"],
            },
        ),
        migrations.CreateModel(
            name="SensorReading",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(db_index=True)),
                (
                    "temperature",
                    models.FloatField(
                        blank=True, help_text="Temperature in °C", null=True
                    ),
                ),
                (
                    "humidity",
                    models.FloatField(
                        blank=True, help_text="Relative Humidity in %", null=True
                    ),
                ),
                (
                    "pressure",
                    models.FloatField(
                        blank=True, help_text="Atmospheric Pressure in hPa", null=True
                    ),
                ),
                (
                    "is_imputed",
                    models.BooleanField(
                        default=False,
                        help_text="True if any value was recovered/imputed",
                    ),
                ),
                (
                    "imputed_temperature",
                    models.FloatField(
                        blank=True,
                        help_text="Recovered temperature if raw was missing/corrupted",
                        null=True,
                    ),
                ),
                (
                    "imputed_humidity",
                    models.FloatField(
                        blank=True,
                        help_text="Recovered humidity if raw was missing/corrupted",
                        null=True,
                    ),
                ),
                (
                    "imputed_pressure",
                    models.FloatField(
                        blank=True,
                        help_text="Recovered pressure if raw was missing/corrupted",
                        null=True,
                    ),
                ),
                (
                    "imputation_confidence",
                    models.FloatField(
                        blank=True,
                        help_text="Confidence score of recovery algorithm (0.0 - 1.0)",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="Station",
            fields=[
                (
                    "station_id",
                    models.CharField(
                        help_text="Unique Station Identifier (e.g. AWS-IND-0101)",
                        max_length=50,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(help_text="Station display name", max_length=150),
                ),
                (
                    "latitude",
                    models.FloatField(help_text="Latitude in decimal degrees"),
                ),
                (
                    "longitude",
                    models.FloatField(help_text="Longitude in decimal degrees"),
                ),
                (
                    "elevation",
                    models.FloatField(
                        default=0.0, help_text="Elevation above sea level in meters"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active / Operational"),
                            ("WARNING", "Warning / Degraded Sensors"),
                            ("CRITICAL", "Critical / Multiple Sensor Faults"),
                            ("OFFLINE", "Offline / Comm Failure"),
                        ],
                        default="ACTIVE",
                        max_length=20,
                    ),
                ),
                (
                    "installation_date",
                    models.DateField(default=django.utils.timezone.now),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["station_id"],
            },
        ),
        migrations.CreateModel(
            name="Alert",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("LOW", "Low Severity"),
                            ("MEDIUM", "Medium Severity"),
                            ("HIGH", "High Severity"),
                            ("CRITICAL", "Critical Severity"),
                        ],
                        max_length=15,
                    ),
                ),
                ("message", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active Alert"),
                            ("ACKNOWLEDGED", "Acknowledged by Operator"),
                            ("RESOLVED", "Resolved"),
                        ],
                        default="ACTIVE",
                        max_length=15,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "anomaly",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="alert",
                        to="core.anomaly",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="OperatorFeedback",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "decision",
                    models.CharField(
                        choices=[
                            ("CONFIRMED_FAULT", "Confirmed Sensor Fault"),
                            ("CONFIRMED_WEATHER", "Confirmed Genuine Extreme Weather"),
                            ("REJECTED", "False Alarm / Incorrect Classification"),
                        ],
                        max_length=25,
                    ),
                ),
                ("comment", models.TextField(blank=True)),
                (
                    "operator_name",
                    models.CharField(default="Duty Meteorologist", max_length=100),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "anomaly",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="feedbacks",
                        to="core.anomaly",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="anomaly",
            name="reading",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="anomalies",
                to="core.sensorreading",
            ),
        ),
        migrations.AddField(
            model_name="sensorreading",
            name="station",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="readings",
                to="core.station",
            ),
        ),
        migrations.CreateModel(
            name="SensorHealth",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sensor_type",
                    models.CharField(
                        choices=[
                            ("TEMPERATURE", "Temperature Sensor"),
                            ("HUMIDITY", "Humidity Sensor"),
                            ("PRESSURE", "Pressure Sensor"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "health_score",
                    models.FloatField(
                        default=100.0,
                        help_text="Health score percentage (0.0% - 100.0%)",
                    ),
                ),
                (
                    "drift_score",
                    models.FloatField(
                        default=0.0, help_text="Accumulative drift bias metric"
                    ),
                ),
                (
                    "failure_count",
                    models.IntegerField(
                        default=0,
                        help_text="Count of detected sensor faults in past window",
                    ),
                ),
                (
                    "missing_count",
                    models.IntegerField(
                        default=0,
                        help_text="Count of missing/null values in past window",
                    ),
                ),
                (
                    "last_checked",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "station",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="health_metrics",
                        to="core.station",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Sensor Health Metrics",
                "ordering": ["station", "sensor_type"],
            },
        ),
        migrations.AddField(
            model_name="anomaly",
            name="station",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="anomalies",
                to="core.station",
            ),
        ),
        migrations.AddIndex(
            model_name="sensorreading",
            index=models.Index(
                fields=["station", "-timestamp"], name="core_sensor_station_87d57e_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="sensorhealth",
            unique_together={("station", "sensor_type")},
        ),
    ]
